---
- name: Create pods using deployment and expose the service for the application
  hosts: localhost
  
  collections:
  - community.kubernetes
  
  tasks: 
  - name: create a deployment
    shell: |
      kubectl --kubeconfig=/root/.kube/config apply -f /etc/ansible/kubernetes/deployment.yaml
    
  - name: create a service
    shell: |
      kubectl --kubeconfig=/root/.kube/config apply -f /etc/ansible/kubernetes/service.yaml
    
  - name: update deployment with new pods if image updated in Nexus
    shell: |
      kubectl --kubeconfig=/root/.kube/config rollout restart deployment.v1.apps/sample-tomcat-deployment
